import {
  ArrowLeft,
  ArrowRight,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  Circle,
  CircleDot,
  ClipboardList,
  Cloud,
  Code2,
  Compass,
  DollarSign,
  Dna,
  FolderOpen,
  Globe,
  Gamepad2,
  GraduationCap,
  HeartHandshake,
  Lightbulb,
  Lock,
  Map,
  Medal,
  Rocket,
  Route,
  ShieldCheck,
  Star,
  Sun,
  Target,
  TrendingUp,
  Trophy,
  Waves,
  Zap,
  Check,
} from 'lucide-react';

export var iconMap = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'book-open': BookOpen,
  bot: Bot,
  'career-aerospace': Rocket,
  'career-biomedical': Dna,
  'career-cloud': Cloud,
  'career-cybersecurity': ShieldCheck,
  'career-data': BarChart3,
  'career-environmental': Globe,
  'career-renewable': Sun,
  'career-robotics': Bot,
  'career-salary': DollarSign,
  'career-software': Code2,
  'career-education': GraduationCap,
  'career-growth': TrendingUp,
  check: Check,
  'decision-point': Target,
  'feature-ai': Bot,
  'feature-game': Gamepad2,
  'feature-level': Trophy,
  'feature-quiz': ClipboardList,
  'market-heatmap': Map,
  'market-overview': CircleDot,
  'market-salary': TrendingUp,
  'market-viability': Target,
  'outcome-book': BookOpen,
  'stat-badges': Medal,
  'stat-decisions': Zap,
  'stat-level': Star,
  'stat-scenarios': Target,
  'badge-decision-maker': Zap,
  'badge-deep-diver': Waves,
  'badge-explorer': Compass,
  'badge-first-step': Route,
  'badge-level-10': Trophy,
  'badge-level-5': Star,
  'badge-quick-thinker': Lightbulb,
  'badge-team-player': HeartHandshake,
  'badge-roadmap': Map,
  'badge-project': Briefcase,
  'badge-portfolio': FolderOpen,
  'badge-gap-closer': Target,
  lock: Lock,
};

export function getIconComponent(iconName) {
  const resolvedIcon = iconMap && iconMap[iconName];
  return resolvedIcon || Circle;
}
